-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-04-05 16:25:38 SGT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on
spool cust_orders.txt

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE orderline CASCADE CONSTRAINTS;

DROP TABLE orders CASCADE CONSTRAINTS;

DROP TABLE prod_category CASCADE CONSTRAINTS;

DROP TABLE product CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE customer (
    cust_no      NUMBER(7) NOT NULL,
    cust_name    VARCHAR2(50) NOT NULL,
    cust_address VARCHAR2(50) NOT NULL,
    cust_phone   CHAR(10),
    cust_level   CHAR(1) NOT NULL
);

ALTER TABLE customer
    ADD CONSTRAINT checkcustlevel CHECK ( cust_level IN ( 'B', 'G', 'S' ) );

COMMENT ON COLUMN customer.cust_no IS
    'Customer Number';

COMMENT ON COLUMN customer.cust_name IS
    'Customer Name';

COMMENT ON COLUMN customer.cust_address IS
    'Customer Address';

COMMENT ON COLUMN customer.cust_phone IS
    'Customer Phone';

COMMENT ON COLUMN customer.cust_level IS
    'Customer level';

ALTER TABLE customer ADD CONSTRAINT entity_1_pk PRIMARY KEY ( cust_no );

CREATE TABLE orderline (
    ol_id         NUMBER(7) NOT NULL,
    ol_qtyordered NUMBER(3) NOT NULL,
    ol_lineprice  NUMBER(8, 2) NOT NULL,
    order_no      NUMBER(7) NOT NULL,
    prod_no       NUMBER(7) NOT NULL
);

COMMENT ON COLUMN orderline.ol_id IS
    'Order Line ID';

COMMENT ON COLUMN orderline.ol_qtyordered IS
    'Order Line Quantity Ordered';

COMMENT ON COLUMN orderline.ol_lineprice IS
    'Order Line Line Price';

ALTER TABLE orderline ADD CONSTRAINT orderline_pk PRIMARY KEY ( ol_id );

ALTER TABLE orderline ADD CONSTRAINT orderline_nk UNIQUE ( prod_no,
                                                           order_no );

CREATE TABLE orders (
    order_no   NUMBER(7) NOT NULL,
    order_date DATE NOT NULL,
    cust_no    NUMBER(7) NOT NULL
);

COMMENT ON COLUMN orders.order_no IS
    'Order Number';

COMMENT ON COLUMN orders.order_date IS
    'Order Date';

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY ( order_no );

CREATE TABLE prod_category (
    pcat_id   NUMBER(4) NOT NULL,
    pcat_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN prod_category.pcat_id IS
    'Product Category ID';

COMMENT ON COLUMN prod_category.pcat_name IS
    'Product Category Name';

ALTER TABLE prod_category ADD CONSTRAINT prod_category_pk PRIMARY KEY ( pcat_id );

CREATE TABLE product (
    prod_no        NUMBER(7) NOT NULL,
    prod_desc      VARCHAR2(50) NOT NULL,
    prod_unitprice NUMBER(7, 2) NOT NULL,
    pcat_id        NUMBER(4) NOT NULL
);

COMMENT ON COLUMN product.prod_no IS
    'Product Number';

COMMENT ON COLUMN product.prod_desc IS
    'Product Description';

COMMENT ON COLUMN product.prod_unitprice IS
    'Product Unit Price';

ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( prod_no );

ALTER TABLE orders
    ADD CONSTRAINT customer_orders FOREIGN KEY ( cust_no )
        REFERENCES customer ( cust_no );

ALTER TABLE orderline
    ADD CONSTRAINT orders_orderline FOREIGN KEY ( order_no )
        REFERENCES orders ( order_no );

ALTER TABLE product
    ADD CONSTRAINT prod_category_product FOREIGN KEY ( pcat_id )
        REFERENCES prod_category ( pcat_id );

ALTER TABLE orderline
    ADD CONSTRAINT product_orderline FOREIGN KEY ( prod_no )
        REFERENCES product ( prod_no );

spool off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
